# Generated by Django 4.2.3 on 2024-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardName', models.CharField(max_length=100, verbose_name='Card Name')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('surname', models.CharField(max_length=100, verbose_name='User lname')),
                ('phone', models.CharField(max_length=100, verbose_name='User phone')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=4, verbose_name='Card password')),
                ('numbercard', models.CharField(max_length=19, verbose_name='Number of Card')),
                ('Check', models.CharField(max_length=100, verbose_name='Checking account')),
                ('Limit', models.CharField(max_length=100, verbose_name='Limit')),
                ('paymentSystem', models.CharField(max_length=100, verbose_name='Payment system')),
                ('ImagePaymentSys', models.ImageField(upload_to='images/')),
                ('Validity', models.DateField(verbose_name='Date Validity')),
                ('CashBack', models.CharField(max_length=100, verbose_name='Summ of cash back')),
                ('CashbackPercentage', models.CharField(max_length=100, verbose_name='Precent of cash back')),
                ('ImageCB', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Кредитная карта',
                'verbose_name_plural': 'Кредитные карты',
            },
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardName', models.CharField(max_length=100, verbose_name='Card Name')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('surname', models.CharField(max_length=100, verbose_name='User lname')),
                ('phone', models.CharField(max_length=100, verbose_name='User phone')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=4, verbose_name='Card password')),
                ('numbercard', models.CharField(max_length=19, verbose_name='Number of Card')),
                ('Check', models.CharField(max_length=100, verbose_name='Checking account')),
                ('paymentSystem', models.CharField(max_length=100, verbose_name='Payment system')),
                ('ImagePaymentSys', models.ImageField(upload_to='images/')),
                ('Validity', models.DateField(verbose_name='Date Validity')),
                ('CashBack', models.CharField(max_length=100, verbose_name='Summ of cash back')),
                ('CashbackPercentage', models.CharField(max_length=100, verbose_name='Precent of cash back')),
                ('ImageCB', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Дебетовая карта',
                'verbose_name_plural': 'Дебетовые карты',
            },
        ),
        migrations.CreateModel(
            name='PlatinumCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardName', models.CharField(max_length=100, verbose_name='Card Name')),
                ('name', models.CharField(max_length=100, verbose_name='User Name')),
                ('surname', models.CharField(max_length=100, verbose_name='User lname')),
                ('phone', models.CharField(max_length=100, verbose_name='User phone')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=4, verbose_name='Card password')),
                ('numbercard', models.CharField(max_length=19, verbose_name='Number of Card')),
                ('Check', models.CharField(max_length=100, verbose_name='Checking account')),
                ('Limit', models.CharField(max_length=100, verbose_name='Limit')),
                ('paymentSystem', models.CharField(max_length=100, verbose_name='Payment system')),
                ('ImagePaymentSys', models.ImageField(upload_to='images/')),
                ('Validity', models.DateField(verbose_name='Date Validity')),
                ('CashBack', models.CharField(max_length=100, verbose_name='Summ of cash back')),
                ('CashbackPercentage', models.CharField(max_length=100, verbose_name='Precent of cash back')),
                ('ImageCB', models.ImageField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Платиновая карта',
                'verbose_name_plural': 'Платиновые карты',
            },
        ),
    ]
