# Generated by Django 4.2.3 on 2024-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageUp', models.ImageField(upload_to='images/')),
                ('ImageDown', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name': 'Картинки', 'verbose_name_plural': 'Картинки'},
        ),
    ]
