# Generated by Django 4.2.3 on 2024-01-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_imagetransfer_alter_transfers_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageTransfer',
        ),
        migrations.AlterModelOptions(
            name='transfers',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
