# Generated by Django 4.2.3 on 2024-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_imagetransfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=100, verbose_name='Отправитель')),
                ('Recipient', models.CharField(max_length=100, verbose_name='Получатель')),
                ('message', models.TextField(max_length=1000, verbose_name='Текст сообщения')),
                ('Date', models.DateField(verbose_name='Дата отправки')),
                ('Time', models.TimeField(verbose_name='Время отправки')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщение',
            },
        ),
    ]
